version: "3"

services:
  node-cache:
    build:
      context: ./
    container_name: node-cache
    tty: true
    entrypoint: sh ./.docker/entrypoint.sh
    ports:
      - 3010:3010
    volumes:
      - ./:/usr/node-cache/app
    networks:
      - node-cache

networks:
  node-cache:
    driver: bridge
