version: "3"

services:
  node-cache:
    build:
      context: ./
    container_name: node-cache
    tty: true
    entrypoint: sh ./.docker/app-entrypoint.sh
    ports:
      - 3010:3010
    volumes:
      - ./:/usr/node-cache/app
    networks:
      - node-cache

  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./.docker/volumes/redis/:/data
    entrypoint: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    networks:
      - node-cache
    extra_hosts:
      - host.docker.internal:172.17.0.1

networks:
  node-cache:
    driver: bridge
